ANTIFILTER_DOMAINS_URL: str = 'https://antifilter.download/list/domains.lst'
SECOND_LEVEL_DOMAIN_SEGMENTS: int = 2
MIN_DOMAIN_LEVEL: int = 1
CASINO_DOMAIN_KEYWORDS = [
    'up-x',
    'upx',
    'vavada',
    'leon',
    'azino',
    'vulcan',
    'vullcan',
    'joycas',
    'joycaz',
    'vulkan',
    'wulcan',
    'vegas',
    'fortuna',
    'pinup',
    '1x',
    '-win',
    '1win',
    'casi',
    'kasi',
    'kazi',
    'caz',
    'gamble',
    'slot',
    'fishk',
    'jackpot',
    'winbig',
    'wager',
    'admiral',
    'bet',
    'poker',
    'p0ker',
    'blackjack',
    'deposit',
    'spin',
    'bonus',
    'roulette',
    'stavki',
    'zerkalo',
]
FRAUD_DOMAIN_KEYWORDS = [
    'fraud',
    'login',
    'signin',
    'bank',
    'secure',
    'verify',
    'account',
    'billing',
    'password',
    'invoice',
    'vzyatka',
    'dengi',
    'strahovanie',
    'invest',
    'lombard',
    'ferma',
    'dolg',
]
ILLEGAL_DOMAIN_KEYWORDS = [
    'rape',
    'gore',
    'kill',
    'child',
    'dead',
    'zoo',
    'girl',
    'diplom',
    'dlplom',
    'djplom',
    'dlploum',
    'sprav',
    'avtomat',
    'prava',
    'prawa',
    'dokument',
    'dokhument',
    'medkn',
    'passport',
    'pasport',
    'propis',
    'udostover',
    'attest',
    'registra',
    '2ndfl',
    'kupit',
]
ADULT_DOMAIN_KEYWORDS = [
    'escort',
    'striptiz',
    'massaj',
    'prostitutk',
    'individualk',
    'individyalk',
    'intim',
    'pytana',
    'bribe',
    'russianbrides',
]
DRUG_DOMAIN_KEYWORDS = [
    'drug',
    'metadon',
    'krokodil',
    'meth',
    'narco',
    'narko',
    'weed',
    'xanax',
    'xanaks',
    'mefedron',
    'amfetamin',
    'cocaine',
    'ecstasy',
    'blacksprut',
    'kokain',
    'anasha',
    'konopl',
    'semya',
    'semena',
    'seed',
    'koks',
    'kraken',
    'krakeen',
    'kaif',
]
CRYPTO_DOMAIN_KEYWORDS = [
    'bitcoin',
    'btc',
    'ethereum',
    'eth',
    'litecoin',
    'ltc',
    'ripple',
    'xrp',
    'dogecoin',
    'doge',
    'crypto',
    'blockchain',
    'mining',
    'stake',
    'wallet',
    'trading',
    'trade',
    'hodl',
    'airdrops',
    'whale',
    'satoshi',
    'ledger',
    'defi',
    'nft',
    'altcoin',
    'p2p',
    'cryptomarket',
    'marketcap',
    'pump',
    'dump',
    'chart',
    'bearmarket',
    'bullmarket',
    'technicalanalysis',
    'fundamentalanalysis',
    'liquidity',
]
KEYWORDS = set(
    CASINO_DOMAIN_KEYWORDS
    + FRAUD_DOMAIN_KEYWORDS
    + ILLEGAL_DOMAIN_KEYWORDS
    + ADULT_DOMAIN_KEYWORDS
    + DRUG_DOMAIN_KEYWORDS
    + CRYPTO_DOMAIN_KEYWORDS
)
SING_BOX_TEMPLATE: dict = {
    'version': 1,
    'rules': [{'domain_suffix': []}],
}
