ANTIFILTER_DOMAINS_URL: str = 'https://antifilter.download/list/domains.lst'
OUTPUT_DIR: str = 'output'
SECOND_LEVEL_DOMAIN_PARTS: int = 2
MIN_REQUIRED_DOMAIN_PARTS: int = 1
HEADERS = {
    'User-Agent': (
        'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) '
        'Gecko/20100101 Firefox/131.0'
    )
}
REQUEST_TIMEOUT: int = 5
SING_BOX_TEMPLATE: dict = {
    'version': 1,
    'rules': [{'domain_suffix': []}],
}
CASINO_DOMAIN_KEYWORDS = [
    'up-x',
    'upx',
    'vavada',
    'leon',
    'azino',
    'vulcan',
    'lcan',
    'vullcan',
    'joycas',
    'joycaz',
    'vulkan',
    'wulcan',
    'vegas',
    'clubnika',
    'fortun',
    'pinup',
    'pin-up',
    'eldor',
    'e1dor',
    'e1d0r',
    'eldara',
    'lucky',
    'mega5',
    'ruletk',
    'ryletk',
    '1x',
    '-win',
    '1win',
    'casi',
    'cassi',
    'cas1',
    'kasi',
    'kazi',
    'caz',
    'gamble',
    'slot',
    'fishk',
    'jackpot',
    'winbig',
    'wager',
    'admiral',
    'adm1ral',
    'bet',
    'dep',
    'poker',
    'p0ker',
    'blackjack',
    'deposit',
    'spin',
    'bonus',
    'roulette',
    'stavki',
    'zerkalo',
    '777',
    'selector',
    'mirror',
    'zerkalo',
]
FRAUD_DOMAIN_KEYWORDS = [
    'fraud',
    'login',
    'signin',
    'bank',
    'secure',
    'verify',
    'money',
    'account',
    'billing',
    'business',
    'password',
    'invoice',
    'vzyatka',
    'dengi',
    'strahovanie',
    'invest',
    'lombard',
    'ferma',
    'dolg',
    'zaym',
    'zaim',
    'kredit',
]
ILLEGAL_DOMAIN_KEYWORDS = [
    'rape',
    'gore',
    'kill',
    'child',
    'dead',
    'zoo',
    'girl',
    'diplom',
    'dlplom',
    'djplom',
    'dlploum',
    'dipllom',
    'sprav',
    'avtomat',
    'prava',
    'prawa',
    'doki',
    'dokument',
    'dokhument',
    'voditelskoe',
    'kupi',
    'medkn',
    'passport',
    'pasport',
    'propis',
    'udostover',
    'attest',
    'registra',
    '2ndfl',
    'kupit',
    'osago',
]
ADULT_DOMAIN_KEYWORDS = [
    'escort',
    'striptiz',
    'massaj',
    'prostitut',
    'prostitutk',
    'prostitytk',
    'individualk',
    'individyalk',
    'intim',
    'putan',
    'pytan',
    'shluh',
    'bribe',
    'russianbrides',
]
DRUG_DOMAIN_KEYWORDS = [
    'drug',
    'metadon',
    'krokodil',
    'meth',
    'narco',
    'narko',
    'weed',
    'xanax',
    'xanaks',
    'mefedron',
    'amfetamin',
    'cocaine',
    'ecstasy',
    'blacksprut',
    'kokain',
    'anasha',
    'konopl',
    'semya',
    'semena',
    'seed',
    'koks',
    'krake',
    'kraken',
    'krakean',
    'krakeen',
    'hydra',
    'kaif',
    'gramm',
    'gashish',
    'zaklad',
]
CRYPTO_DOMAIN_KEYWORDS = [
    'bitcoin',
    'btc',
    'ethereum',
    'eth',
    'litecoin',
    'ltc',
    'ripple',
    'xrp',
    'dogecoin',
    'doge',
    'crypto',
    'blockchain',
    'mining',
    'stake',
    'wallet',
    'trading',
    'trade',
    'hodl',
    'airdrops',
    'whale',
    'satoshi',
    'ledger',
    'defi',
    'nft',
    'altcoin',
    'p2p',
    'cryptomarket',
    'marketcap',
    'pump',
    'dump',
    'chart',
    'bearmarket',
    'bullmarket',
    'technicalanalysis',
    'fundamentalanalysis',
    'liquidity',
]
OPT_DOMAIN_KEYWORDS = [
    'google',
    'pages.dev',
    'github.io',
    'ooguy.com'
]
DOMAIN_KEYWORDS = set(
    CASINO_DOMAIN_KEYWORDS
    + FRAUD_DOMAIN_KEYWORDS
    + ILLEGAL_DOMAIN_KEYWORDS
    + ADULT_DOMAIN_KEYWORDS
    + DRUG_DOMAIN_KEYWORDS
    + CRYPTO_DOMAIN_KEYWORDS
    + OPT_DOMAIN_KEYWORDS
)
